const currencyListActionTypes = {
  REQUEST_RATES_PENDING: "REQUEST_RATES_PENDING",
  REQUEST_RATES_SUCCESS: "REQUEST_RATES_SUCCESS",
  REQUEST_RATES_FAILED: "REQUEST_RATES_FAILED",
  ADD_CURRENCY: "ADD_CURRENCY",
  CLEAR_CURRENCY: "CLEAR_CURRENCY",
  REMOVE_CURRENCY: "REMOVE_CURRENCY",
  HANDLE_CHANGE: "HANDLE_CHANGE",
  HANDLE_POPUP_WINDOW: "HANDLE_POPUP_WINDOW"
};

export default currencyListActionTypes;
